/**
 * The two-sided tokenizer canary.
 *
 * f270ee9 closed one hole and left another open. Its probe asks the running
 * server to `/detokenize` sampled ids and compares the result against the
 * artifact's token table. That proves one direction:
 *
 *     token id -> bytes
 *
 * It does not prove the direction prompt counts actually depend on:
 *
 *     bytes -> token ids
 *
 * A runtime can hold the same token table and still segment text differently:
 * `tokenizer.ggml.merges` decides how pieces combine, `tokenizer.ggml.pre`
 * decides where the splitting starts, added-token and special-token handling
 * decide whether `<|im_end|>` is one token or six. `--override-kv` reaches all
 * of them at load time without touching a byte of the file. Under any of those
 * substitutions every decode sample still passes — the table is unchanged —
 * while `usage.prompt_tokens` comes from a tokenizer nobody described.
 *
 * So decode-only verification is not tokenizer identity, and this contract
 * refuses to let it be reported as such. `decodeCanaryVerified` and
 * `encodeCanaryVerified` are separate booleans precisely so the weaker one
 * cannot be spent as the stronger.
 *
 * **What this is not.** A sampled corpus is behavioural evidence, not a proof
 * of tokenizer equivalence. Proving equivalence would mean enumerating an
 * infinite input space, or reimplementing byte-level BPE here and comparing
 * implementations — a second tokenizer being a second thing that can be wrong.
 * The claim is bounded and stated in `coverageNote`: these exact inputs produce
 * these exact ids on this backend instance. A substitution that changes
 * segmentation anywhere the corpus reaches is caught; one that changes it only
 * where the corpus does not reach is not.
 */
import type { ArtifactDigest } from './identity.js';

export const TOKENIZER_CANARY_SCHEMA = 'bokahli.tokenizer-canary.v1';

/**
 * Where a canary's expected values came from.
 *
 * The distinction that matters is not which tool ran but whether the answer
 * came from somewhere other than the thing being tested. An expectation
 * generated by the live backend and then compared back to that same backend is
 * a tautology: it passes whatever the backend does, including the substitution
 * the canary exists to catch.
 */
export type CanaryReferenceMethod =
  /**
   * `llama-tokenize` with `vocab_only`, run as a separate short-lived process
   * against the same GGUF. No server contact, no GPU, no inference. This is
   * the encode authority.
   */
  | 'llama-tokenize-vocab-only'
  /**
   * The artifact's own `tokenizer.ggml.tokens` table, read from the file whose
   * digest Bokahli verified. This is the decode authority.
   */
  | 'gguf-token-table'
  /**
   * Produced by a running llama-server. Never independent, and never sufficient
   * for `encodeCanaryVerified`; carried as a value only so that a suite built
   * this way is *labelled* rather than indistinguishable.
   */
  | 'live-backend';

/** True only for methods that do not depend on a running backend. */
export function canaryReferenceIsIndependent(m: CanaryReferenceMethod): boolean {
  return m === 'llama-tokenize-vocab-only' || m === 'gguf-token-table';
}

export interface CanaryReference {
  readonly method: CanaryReferenceMethod;
  /** `basename:sha256` of the objects that produced the expectations. */
  readonly generatorComponents: readonly string[];
  /** sha256 over those components. Identity of the generator, not a path. */
  readonly generatorDigest: string | null;
  /** Build string the generator reported, when it reports one. */
  readonly generatorBuild: string | null;
  /**
   * The backend instance that produced these values, when one did.
   *
   * Null for an independent method. Non-null makes self-authorisation
   * detectable: a verifier refuses a suite whose expectations came from the
   * instance it is verifying.
   */
  readonly producedByBackendInstanceId: string | null;
  readonly note: string;
}

/**
 * bytes -> ids. The direction that governs prompt counts.
 *
 * Input is base64 of the exact bytes rather than a JSON string. The corpus
 * contains CRLF, combining marks, lone whitespace runs and a ZWJ emoji
 * sequence; a JSON string survives a round trip through most tools but not all
 * of them, and a corpus an editor can normalise is a corpus that silently
 * stops testing what it was written to test.
 */
export interface TokenizerEncodeCase {
  readonly id: string;
  /** Which pre-tokenizer property this case exercises. */
  readonly note: string;
  readonly inputBase64: string;
  readonly expectedIds: readonly number[];
}

/**
 * ids -> bytes. One id per case.
 *
 * Single ids, because detokenizing a batch concatenates the pieces and an
 * offsetting pair of differences would cancel. Multi-id detokenization is
 * deliberately not canaried: `common_detokenize` applies its own spacing rules
 * on top of the vocabulary, so an expectation derived from the token table
 * could fail on a correct deployment — and a canary that fails when nothing is
 * wrong gets switched off, which is worse than the gap.
 */
export interface TokenizerDecodeCase {
  readonly id: string;
  readonly note: string;
  readonly tokenId: number;
  readonly expectedBytesBase64: string;
}

export interface TokenizerCanarySuite {
  readonly schemaVersion: typeof TOKENIZER_CANARY_SCHEMA;
  /** Stable name, e.g. `qwen35-broad.v1`. Changes when the corpus changes. */
  readonly suiteId: string;
  /** The artifact these expectations describe. A suite is not portable. */
  readonly artifactDigest: ArtifactDigest;
  /** The tokenizer metadata digest at generation time. */
  readonly tokenizerMetadataDigest: ArtifactDigest;
  readonly vocabSize: number;
  /**
   * The encode settings the expectations were produced under.
   *
   * Pinned rather than defaulted: llama-server's `/tokenize` defaults
   * `parse_special` to true and `add_special` to false, and a canary generated
   * under one setting and verified under another fails for a reason that has
   * nothing to do with tokenizer identity.
   */
  readonly encodeSettings: {
    readonly addSpecial: boolean;
    readonly parseSpecial: boolean;
  };
  readonly encodeReference: CanaryReference;
  readonly decodeReference: CanaryReference;
  readonly encode: readonly TokenizerEncodeCase[];
  readonly decode: readonly TokenizerDecodeCase[];
  /** sha256 over the canonical payload: every field above except this one. */
  readonly payloadHash: string;
  readonly generatedAt: string;
  /** Corpus dimensions, for a reader deciding whether coverage is adequate. */
  readonly coverage: readonly string[];
  readonly note: string;
}

/**
 * What a verification run established, against which instance, and when.
 *
 * `encodeCanaryVerified` requires every encode case to pass. There is no
 * partial credit: a suite where one case fails and twenty-nine pass describes a
 * runtime that segments text differently from the one the expectations came
 * from, and the failure is the finding.
 */
export interface TokenizerCanaryResult {
  readonly schemaVersion: string | null;
  readonly canarySuiteId: string | null;
  readonly canarySuiteHash: string | null;
  readonly decodeCanaryVerified: boolean;
  readonly encodeCanaryVerified: boolean;
  readonly encodeChecked: number;
  readonly encodeMatched: number;
  readonly decodeChecked: number;
  readonly decodeMatched: number;
  /** Case ids that failed, bounded so a broken runtime cannot inflate a response. */
  readonly failedCaseIds: readonly string[];
  readonly encodeReferenceMethod: CanaryReferenceMethod | null;
  readonly decodeReferenceMethod: CanaryReferenceMethod | null;
  /** The instance the probe ran against. A verification describes one process. */
  readonly verifiedBackendInstanceId: string | null;
  readonly verifiedAt: string;
  readonly reasons: readonly string[];
  /** The bound on the claim, carried with the claim. */
  /**
   * Set when the *host* could not be trusted to convert bytes, rather than the
   * runtime disagreeing about tokenization.
   *
   * `Buffer.prototype.toString('base64')` was measured returning a wrong
   * character roughly once in a thousand calls on one physical core of the
   * deployment machine — silently, with no machine check and with the source
   * bytes provably unchanged. That comparison used to decide
   * `decodeCanaryVerified`, so a host fault presented as "the runtime decodes
   * differently from the artifact token table" and discarded an otherwise valid
   * attempt as a tokenizer-provenance problem.
   *
   * When this is non-null both canaries are unverified and the reason is this
   * one. A consumer must treat it as a statement about the machine — a
   * runtime-unhealthy outcome — and never as degraded token provenance, and
   * never as a statement about the model.
   */
  readonly hostIntegrityFault: string | null;
  /**
   * Which base64 implementation produced and checked the pinned encodings.
   *
   * Bound into the result because "encoded with the audited implementation" is
   * a claim about how bytes were converted, and a claim nobody records is a
   * claim nobody can check.
   */
  readonly baseEncodingImplementation: string;
  readonly coverageNote: string;
}
