/**
 * The two-sided tokenizer canary.
 *
 * f270ee9 closed one hole and left another open. Its probe asks the running
 * server to `/detokenize` sampled ids and compares the result against the
 * artifact's token table. That proves one direction:
 *
 *     token id -> bytes
 *
 * It does not prove the direction prompt counts actually depend on:
 *
 *     bytes -> token ids
 *
 * A runtime can hold the same token table and still segment text differently:
 * `tokenizer.ggml.merges` decides how pieces combine, `tokenizer.ggml.pre`
 * decides where the splitting starts, added-token and special-token handling
 * decide whether `<|im_end|>` is one token or six. `--override-kv` reaches all
 * of them at load time without touching a byte of the file. Under any of those
 * substitutions every decode sample still passes — the table is unchanged —
 * while `usage.prompt_tokens` comes from a tokenizer nobody described.
 *
 * So decode-only verification is not tokenizer identity, and this contract
 * refuses to let it be reported as such. `decodeCanaryVerified` and
 * `encodeCanaryVerified` are separate booleans precisely so the weaker one
 * cannot be spent as the stronger.
 *
 * **What this is not.** A sampled corpus is behavioural evidence, not a proof
 * of tokenizer equivalence. Proving equivalence would mean enumerating an
 * infinite input space, or reimplementing byte-level BPE here and comparing
 * implementations — a second tokenizer being a second thing that can be wrong.
 * The claim is bounded and stated in `coverageNote`: these exact inputs produce
 * these exact ids on this backend instance. A substitution that changes
 * segmentation anywhere the corpus reaches is caught; one that changes it only
 * where the corpus does not reach is not.
 */
import { createHash } from 'node:crypto';
import type { ArtifactDigest } from './identity.js';

export const TOKENIZER_CANARY_SCHEMA = 'bokahli.tokenizer-canary.v1';

/**
 * Where a canary's expected values came from.
 *
 * The distinction that matters is not which tool ran but whether the answer
 * came from somewhere other than the thing being tested. An expectation
 * generated by the live backend and then compared back to that same backend is
 * a tautology: it passes whatever the backend does, including the substitution
 * the canary exists to catch.
 */
export type CanaryReferenceMethod =
  /**
   * `llama-tokenize` with `vocab_only`, run as a separate short-lived process
   * against the same GGUF. No server contact, no GPU, no inference. This is
   * the encode authority.
   */
  | 'llama-tokenize-vocab-only'
  /**
   * The artifact's own `tokenizer.ggml.tokens` table, read from the file whose
   * digest Bokahli verified. This is the decode authority.
   */
  | 'gguf-token-table'
  /**
   * Produced by a running llama-server. Never independent, and never sufficient
   * for `encodeCanaryVerified`; carried as a value only so that a suite built
   * this way is *labelled* rather than indistinguishable.
   */
  | 'live-backend';

/** True only for methods that do not depend on a running backend. */
export function canaryReferenceIsIndependent(m: CanaryReferenceMethod): boolean {
  return m === 'llama-tokenize-vocab-only' || m === 'gguf-token-table';
}

export interface CanaryReference {
  readonly method: CanaryReferenceMethod;
  /** `basename:sha256` of the objects that produced the expectations. */
  readonly generatorComponents: readonly string[];
  /** sha256 over those components. Identity of the generator, not a path. */
  readonly generatorDigest: string | null;
  /** Build string the generator reported, when it reports one. */
  readonly generatorBuild: string | null;
  /**
   * The backend instance that produced these values, when one did.
   *
   * Null for an independent method. Non-null makes self-authorisation
   * detectable: a verifier refuses a suite whose expectations came from the
   * instance it is verifying.
   */
  readonly producedByBackendInstanceId: string | null;
  readonly note: string;
}

/**
 * bytes -> ids. The direction that governs prompt counts.
 *
 * Input is base64 of the exact bytes rather than a JSON string. The corpus
 * contains CRLF, combining marks, lone whitespace runs and a ZWJ emoji
 * sequence; a JSON string survives a round trip through most tools but not all
 * of them, and a corpus an editor can normalise is a corpus that silently
 * stops testing what it was written to test.
 */
export interface TokenizerEncodeCase {
  readonly id: string;
  /** Which pre-tokenizer property this case exercises. */
  readonly note: string;
  readonly inputBase64: string;
  readonly expectedIds: readonly number[];
}

/**
 * ids -> bytes. One id per case.
 *
 * Single ids, because detokenizing a batch concatenates the pieces and an
 * offsetting pair of differences would cancel. Multi-id detokenization is
 * deliberately not canaried: `common_detokenize` applies its own spacing rules
 * on top of the vocabulary, so an expectation derived from the token table
 * could fail on a correct deployment — and a canary that fails when nothing is
 * wrong gets switched off, which is worse than the gap.
 */
export interface TokenizerDecodeCase {
  readonly id: string;
  readonly note: string;
  readonly tokenId: number;
  readonly expectedBytesBase64: string;
}

export interface TokenizerCanarySuite {
  readonly schemaVersion: typeof TOKENIZER_CANARY_SCHEMA;
  /**
   * The suite's identity, **derived** from its own contents. Never authored.
   *
   * See `canarySuiteIdentity`. `validateCanarySuite` recomputes it and refuses
   * a suite whose declared id is not the one its contents produce, so this
   * field cannot say one thing while the suite is another.
   */
  readonly suiteId: string;
  /**
   * `tokenizer.ggml.model` as read from the artifact, e.g. `gpt2`, `gemma4`.
   *
   * Read from the file whose digest Bokahli verified, never chosen. Null only
   * when the artifact declares none, which is itself reported rather than
   * filled in.
   */
  readonly tokenizerFamily: string | null;
  /** `tokenizer.ggml.pre`, the pre-tokenizer variant. Null when absent. */
  readonly tokenizerPre: string | null;
  /** The artifact these expectations describe. A suite is not portable. */
  readonly artifactDigest: ArtifactDigest;
  /** The tokenizer metadata digest at generation time. */
  readonly tokenizerMetadataDigest: ArtifactDigest;
  readonly vocabSize: number;
  /**
   * The encode settings the expectations were produced under.
   *
   * Pinned rather than defaulted: llama-server's `/tokenize` defaults
   * `parse_special` to true and `add_special` to false, and a canary generated
   * under one setting and verified under another fails for a reason that has
   * nothing to do with tokenizer identity.
   */
  readonly encodeSettings: {
    readonly addSpecial: boolean;
    readonly parseSpecial: boolean;
  };
  readonly encodeReference: CanaryReference;
  readonly decodeReference: CanaryReference;
  readonly encode: readonly TokenizerEncodeCase[];
  readonly decode: readonly TokenizerDecodeCase[];
  /** sha256 over the canonical payload: every field above except this one. */
  readonly payloadHash: string;
  readonly generatedAt: string;
  /** Corpus dimensions, for a reader deciding whether coverage is adequate. */
  readonly coverage: readonly string[];
  readonly note: string;
}

/**
 * The corpus's identity: what was asked, not what the answers were.
 *
 * Over case ids and inputs only, deliberately. The *expected* ids differ
 * between two tokenizers by design, so hashing them would make every artifact's
 * corpus look like a different corpus and destroy the one thing this component
 * is for — saying that two suites asked the same questions.
 */
export function canaryCorpusDigest(encode: readonly TokenizerEncodeCase[]): string {
  const payload = encode.map((c) => `${c.id}:${c.inputBase64}`).join('\n');
  return createHash('sha256').update(payload).digest('hex');
}

/** Keep a family or pre-tokenizer name to characters an identifier may carry. */
function slug(v: string | null): string {
  if (v === null) return '';
  const cleaned = v.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return cleaned.slice(0, 32);
}

/**
 * A canary suite's identity, derived from the suite.
 *
 * ## Why this is not a constant
 *
 * It was one. `scripts/generate-tokenizer-canary.mjs` carried
 * `const SUITE_ID = 'qwen35-broad.v1'` and stamped it on every suite it
 * produced, so both Gemma artifacts shipped canaries announcing a Qwen
 * tokenizer — in the catalog, in `/health/ready`, and inside every attestation
 * a Gemma-served request produced. The bindings underneath were exact the whole
 * time: artifact digest, tokenizer metadata digest and backend instance were
 * all checked, and a Qwen suite could never have verified against a Gemma
 * artifact. What was wrong was the *label*, which is the part a human reads,
 * and a label that says Qwen over Gemma evidence is a false statement whether
 * or not the machine is fooled by it.
 *
 * The fix is not a better constant. A name that can be typed can be typed
 * wrongly, and the next artifact would have inherited whatever the last one
 * said. So the id is computed from three facts the suite already carries and
 * cannot misreport:
 *
 *   family    `tokenizer.ggml.model` (+ `.pre`) read out of the artifact whose
 *             digest was verified before generation began. Never a marketing
 *             name — `gpt2` and `gemma4` are what the files actually say.
 *   corpus    a digest over the questions asked, so a changed corpus is a
 *             changed identity, which is what the old `.v1` suffix was
 *             gesturing at.
 *   tokenizer a prefix of the tokenizer metadata digest, so a suite generated
 *             against different metadata cannot wear this identity.
 *
 * `validateCanarySuite` recomputes it, which turns the label into a checked
 * claim rather than a decoration. This does not replace any binding: the exact
 * digest comparisons in `verifyTokenizerCanary` are untouched and still decide
 * whether a canary applies.
 *
 * Both Qwen quantisations share tokenizer metadata and so share a suite id.
 * That is correct and not a collision — it is the same corpus put to the same
 * tokenizer. Which *artifact* a suite belongs to is `artifactDigest`, checked
 * separately and exactly.
 */
export function canarySuiteIdentity(parts: {
  readonly tokenizerFamily: string | null;
  readonly tokenizerPre: string | null;
  readonly tokenizerMetadataDigest: string;
  readonly encode: readonly TokenizerEncodeCase[];
}): string {
  const fam = slug(parts.tokenizerFamily) || 'unknown-family';
  const pre = slug(parts.tokenizerPre);
  const family = pre === '' ? fam : `${fam}-${pre}`;
  const corpus = canaryCorpusDigest(parts.encode).slice(0, 8);
  const tok = parts.tokenizerMetadataDigest.replace(/^sha256:/, '').slice(0, 12);
  return `tokcanary.v1.${family}.c${corpus}.t${tok}`;
}

/**
 * What a verification run established, against which instance, and when.
 *
 * `encodeCanaryVerified` requires every encode case to pass. There is no
 * partial credit: a suite where one case fails and twenty-nine pass describes a
 * runtime that segments text differently from the one the expectations came
 * from, and the failure is the finding.
 */
export interface TokenizerCanaryResult {
  readonly schemaVersion: string | null;
  readonly canarySuiteId: string | null;
  readonly canarySuiteHash: string | null;
  readonly decodeCanaryVerified: boolean;
  readonly encodeCanaryVerified: boolean;
  readonly encodeChecked: number;
  readonly encodeMatched: number;
  readonly decodeChecked: number;
  readonly decodeMatched: number;
  /** Case ids that failed, bounded so a broken runtime cannot inflate a response. */
  readonly failedCaseIds: readonly string[];
  readonly encodeReferenceMethod: CanaryReferenceMethod | null;
  readonly decodeReferenceMethod: CanaryReferenceMethod | null;
  /** The instance the probe ran against. A verification describes one process. */
  readonly verifiedBackendInstanceId: string | null;
  readonly verifiedAt: string;
  readonly reasons: readonly string[];
  /** The bound on the claim, carried with the claim. */
  /**
   * Set when the *host* could not be trusted to convert bytes, rather than the
   * runtime disagreeing about tokenization.
   *
   * `Buffer.prototype.toString('base64')` was measured returning a wrong
   * character roughly once in a thousand calls on one physical core of the
   * deployment machine — silently, with no machine check and with the source
   * bytes provably unchanged. That comparison used to decide
   * `decodeCanaryVerified`, so a host fault presented as "the runtime decodes
   * differently from the artifact token table" and discarded an otherwise valid
   * attempt as a tokenizer-provenance problem.
   *
   * When this is non-null both canaries are unverified and the reason is this
   * one. A consumer must treat it as a statement about the machine — a
   * runtime-unhealthy outcome — and never as degraded token provenance, and
   * never as a statement about the model.
   */
  readonly hostIntegrityFault: string | null;
  /**
   * Which base64 implementation produced and checked the pinned encodings.
   *
   * Bound into the result because "encoded with the audited implementation" is
   * a claim about how bytes were converted, and a claim nobody records is a
   * claim nobody can check.
   */
  readonly baseEncodingImplementation: string;
  readonly coverageNote: string;
}
