/**
 * Ask the running server what tokenizer it actually loaded.
 *
 * Every other tokenizer fact Bokahli has describes a *file*. That was the hole
 * the audit of 4d8ced6 opened: llama.cpp's `--override-kv` replaces GGUF
 * metadata at load time without touching the artifact, so the digest matches,
 * the path matches, attestation passes, the vocabulary size is unchanged — and
 * the tokenizer splitting text is not the one Bokahli described. Vocabulary-size
 * equality is *consistent* with the runtime having loaded our file. It is not
 * evidence of it, and the previous version treated it as the binding.
 *
 * The fix is behavioural. `/detokenize` returns the text for a list of ids,
 * which reads the vocabulary table the process actually holds. Comparing that
 * against the artifact's own token table, at sampled indices, catches a
 * substituted vocabulary in a way no metadata comparison can.
 *
 * That was still only half the check, and the half that matters least. A
 * decode probe reads the token *table*; it does not read the merges, the
 * pre-tokenizer, or the added-token configuration, and those are what turn text
 * into ids. `--override-kv` reaches all three while leaving the table alone, so
 * every sample here can pass while every `usage.prompt_tokens` is produced by a
 * tokenizer nobody described. The encode direction is therefore checked too,
 * against a corpus pinned in the catalog with expectations generated by an
 * independent process — see `tokenizer-canary.ts`. This module runs both and
 * reports them separately.
 *
 * Two limits remain, stated rather than papered over:
 *
 *   - Coverage is behavioural, over a finite corpus. It is not a proof of
 *     tokenizer equivalence, and `coverageNote` says so wherever the result
 *     travels. `segmentationDigest` adds comparability between runs on top.
 *   - It is about one process. The proof carries the backend instance id, and a
 *     probe from a previous instance proves nothing about the current one.
 *
 * Neither endpoint runs the model: no decode, no slot, no GPU work.
 */
import { createHash } from 'node:crypto';
import type { RuntimeTokenizerProof, TokenizerCanarySuite } from '@bokahli/contracts';
import { verifyTokenizerCanary } from './tokenizer-canary.js';

/**
 * A fixed probe whose segmentation exercises the parts of a pre-tokenizer that
 * differ between variants: repeated leading whitespace, a special-token
 * literal, non-Latin script, and digit grouping.
 */
export const PROBE_TEXT = 'Bokahli probe:  \t 日本語 0123456789 <|im_end|> end';

/** Bumped whenever the probe text or the sampling rule changes. */
export const PROBE_ID = 'bokahli.tokenizer-probe.v1';

/** How many vocabulary entries to check. */
const SAMPLE_COUNT = 24;

export interface TokenizerProbeSources {
  /**
   * POST /tokenize. Returns token ids.
   *
   * The settings are passed rather than defaulted because llama-server decides
   * them for us otherwise — `add_special` false, `parse_special` true — and a
   * canary generated under one setting and checked under another fails for a
   * reason that has nothing to do with tokenizer identity.
   */
  readonly tokenize: (
    text: string,
    opts: { readonly addSpecial: boolean; readonly parseSpecial: boolean },
  ) => Promise<readonly number[]>;
  /** POST /detokenize. Returns the concatenated text for those ids. */
  readonly detokenize: (ids: readonly number[]) => Promise<string>;
  readonly now: () => Date;
}

/**
 * Which vocabulary indices to sample.
 *
 * Deterministic from the vocabulary size so two runs against the same artifact
 * check the same entries and their results are comparable. Spread across the
 * range and anchored at both ends, because a substituted vocabulary is most
 * likely to differ in the added-token region near the top rather than in the
 * ASCII entries near the bottom — sampling only the start would miss exactly
 * the case worth catching.
 */
export function sampleIds(vocabSize: number, count = SAMPLE_COUNT): readonly number[] {
  if (vocabSize <= 0) return [];
  const ids = new Set<number>();
  ids.add(0);
  ids.add(vocabSize - 1);
  const step = Math.max(1, Math.floor(vocabSize / Math.max(1, count - 2)));
  for (let i = step; i < vocabSize - 1 && ids.size < count; i += step) ids.add(i);
  return [...ids].sort((a, b) => a - b);
}

export interface ProbeInputs {
  /** The artifact's own token table, from GGUF. */
  readonly artifactTokens: readonly string[] | null;
  /**
   * `tokenizer.ggml.token_type`, parallel to the table.
   *
   * Without it the probe cannot tell a real vocabulary entry from the UNUSED
   * padding that fills a vocabulary out to a round size, and llama.cpp renders
   * padding as the empty string. The top anchor of the sample lands squarely in
   * that padding on this artifact — 243 of 248,320 entries — so a probe run
   * without types reports a mismatch against a healthy backend.
   */
  readonly artifactTokenTypes?: Int32Array | readonly number[] | null;
  readonly backendInstanceId: string | null;
  /**
   * The pinned two-sided canary for this artifact, when one exists.
   *
   * Null is a real state, not an oversight: an artifact that has been installed
   * but not prepared has no canary, and the honest consequence is that its
   * token counts stay unproven. The sampled probe below still runs — it is
   * cheap and it still catches a swapped vocabulary — but a decode-only result
   * is never enough for a `runtime_tokenizer` claim.
   */
  readonly canarySuite?: TokenizerCanarySuite | null;
  readonly artifactDigest?: string;
  readonly tokenizerMetadataDigest?: string | null;
}

/**
 * Run the probe. Never throws: a probe that could not run leaves the claim
 * unproven, which is the correct outcome and not an error the caller must
 * handle.
 */
export async function probeRuntimeTokenizer(
  inputs: ProbeInputs,
  sources: TokenizerProbeSources,
): Promise<RuntimeTokenizerProof> {
  const observedAt = sources.now().toISOString();
  const suite = inputs.canarySuite ?? null;

  // The canary runs first and independently of the sampled probe: its verdict
  // must not depend on whether the cheaper check happened to pass, and a caller
  // reading `canary` must find the same answer either way.
  const canary = await verifyTokenizerCanary(
    suite,
    {
      artifactDigest: inputs.artifactDigest ?? '',
      tokenizerMetadataDigest: inputs.tokenizerMetadataDigest ?? null,
      backendInstanceId: inputs.backendInstanceId,
    },
    {
      tokenize: sources.tokenize,
      detokenize: sources.detokenize,
      now: sources.now,
    },
  );

  const base = {
    // Naming the method after what was actually done. A decode-only run must
    // not be able to present itself as the two-sided one.
    method: (suite === null ? 'runtime-vocab-probe' : 'runtime-canary-probe') as
      | 'runtime-vocab-probe'
      | 'runtime-canary-probe',
    backendInstanceId: inputs.backendInstanceId,
    observedAt,
    canary,
  };

  if (inputs.artifactTokens === null || inputs.artifactTokens.length === 0) {
    return {
      ...base, matches: false, samplesChecked: 0, samplesMatched: 0,
      segmentationDigest: null,
      detail: 'artifact token table unavailable, so there is nothing to compare against',
    };
  }

  const sampled = sampleIds(inputs.artifactTokens.length);
  // Ids whose bytes are not valid UTF-8 in isolation are dropped before the
  // comparison rather than counted as matches. Both sides render such a
  // fragment as U+FFFD, so they agree — a match produced by two independent
  // failures, which is a false positive rather than evidence.
  const types = inputs.artifactTokenTypes ?? null;
  const ids: number[] = [];
  for (const id of sampled) {
    // UNUSED (5) and UNDEFINED (0) entries are padding. The runtime renders them
    // as the empty string, so pinning the artifact's stored text for one would
    // fail a healthy backend.
    const ty = types === null ? null : (types[id] ?? null);
    if (ty === 0 || ty === 5) continue;
    const bytes = decodeByteLevelBytes(inputs.artifactTokens[id] as string);
    if (bytes !== null && isSelfContainedUtf8(bytes)) ids.push(id);
  }
  const skipped = sampled.length - ids.length;

  if (ids.length === 0) {
    return {
      ...base, matches: false, samplesChecked: 0, samplesMatched: 0,
      segmentationDigest: null,
      detail: 'no sampled vocabulary entry was comparable over this transport',
    };
  }

  let matched = 0;
  let firstMismatch: number | null = null;

  // One id at a time. Detokenizing the batch would concatenate the pieces and
  // an offsetting pair of differences could cancel out; per-id comparison
  // cannot be fooled that way.
  for (const id of ids) {
    let got: string;
    try {
      got = await sources.detokenize([id]);
    } catch (err) {
      return {
        ...base, matches: false, samplesChecked: ids.length, samplesMatched: matched,
        segmentationDigest: null,
        detail: `runtime detokenize failed (${(err as Error).name})`,
      };
    }
    // GGUF stores byte-level BPE tokens in their encoded form; the runtime
    // returns decoded text. Compare on the decoded form of our own entry so the
    // two are in the same representation.
    const want = decodeByteLevel(inputs.artifactTokens[id] as string);
    if (got === want) matched += 1;
    else if (firstMismatch === null) firstMismatch = id;
  }

  let segmentationDigest: string | null = null;
  try {
    const tokens = await sources.tokenize(PROBE_TEXT, {
      addSpecial: suite?.encodeSettings.addSpecial ?? false,
      parseSpecial: suite?.encodeSettings.parseSpecial ?? true,
    });
    segmentationDigest = `sha256:${createHash('sha256')
      .update(`${PROBE_ID}\n${tokens.join(',')}`)
      .digest('hex')}`;
  } catch {
    // The vocabulary comparison is the binding; segmentation is comparability
    // metadata. Losing it weakens the record without invalidating the proof.
  }

  const matches = matched === ids.length;
  return {
    ...base,
    matches,
    samplesChecked: ids.length,
    samplesMatched: matched,
    segmentationDigest,
    detail: matches
      ? (skipped === 0
          ? null
          : `${skipped} sampled entries were not comparable over this transport and were skipped`)
      : `runtime vocabulary differs from the artifact at id ${String(firstMismatch)} ` +
        `(${matched}/${ids.length} comparable entries matched, ${skipped} skipped)`,
  };
}

/**
 * GPT-2 byte-level BPE reverses a fixed printable mapping.
 *
 * `bytes_to_unicode` sends bytes 33-126, 161-172 and 174-255 to the codepoint
 * equal to the byte, and displaces the remaining 68 bytes — the C0 range, DEL,
 * C1, and 0xAD — into U+0100..U+0143. So `\u0120` is a space and `\u010A` a
 * newline, and everything outside the displaced block is *its own byte value*.
 *
 * That last clause is where the first version of this function was wrong. It
 * fell through to `Buffer.from(ch, 'utf8')`, which is correct only for ASCII:
 * for U+00E4 it produced the two bytes `c3 a4` instead of the one byte `e4`, so
 * every multi-byte token — every CJK entry, every accented word — decoded to
 * mojibake and compared unequal. The sampled probe would have reported
 * `matches: false` against a perfectly healthy backend, which a live run of the
 * canary caught before this shipped: 20 of 33 sampled vocabulary entries failed
 * for that reason alone.
 *
 * Returns null when a codepoint falls outside the byte-level alphabet, which
 * means the token is not byte-level encoded and this decoder has no business
 * guessing at it.
 */
export function decodeByteLevelBytes(token: string): Buffer | null {
  const bytes: number[] = [];
  for (const ch of token) {
    const c = ch.codePointAt(0) ?? 0;
    if (c >= 0x0100 && c <= 0x0120) bytes.push(c - 0x0100);             // bytes 0..32
    else if (c >= 0x0121 && c <= 0x0142) bytes.push(c - 0x0121 + 0x7f); // bytes 127..160
    else if (c === 0x0143) bytes.push(0xad);
    else if (c <= 0xff) bytes.push(c);                                  // the byte is the codepoint
    else return null;
  }
  return Buffer.from(bytes);
}

/**
 * Whether a byte sequence is valid UTF-8 on its own.
 *
 * Tokens that are fragments of a multi-byte sequence are not. They matter here
 * because both sides of a comparison would render such a fragment as U+FFFD and
 * therefore *match* — a false positive produced by two independent failures
 * agreeing, which is the worst kind. Such ids are excluded rather than counted.
 */
export function isSelfContainedUtf8(bytes: Buffer): boolean {
  return Buffer.from(bytes.toString('utf8'), 'utf8').equals(bytes);
}

/** The decoded text of a byte-level token, or null when it is not representable. */
export function decodeByteLevel(token: string): string {
  const bytes = decodeByteLevelBytes(token);
  return bytes === null ? '' : bytes.toString('utf8');
}
