/**
 * Verify a pinned tokenizer canary against the running backend.
 *
 * The canary is two-sided on purpose. f270ee9's probe asked the runtime to
 * decode sampled ids and compared the bytes; that is a real check and it is
 * blind in the direction that matters. Prompt counts come from encoding, and
 * `--override-kv` can replace `tokenizer.ggml.merges`, `tokenizer.ggml.pre`,
 * or the added-token configuration at load time while leaving the token table —
 * the only thing a decode probe reads — completely untouched. Every decode
 * sample passes; every count is wrong.
 *
 * So this module checks both directions, and reports them as two booleans that
 * cannot be substituted for one another.
 *
 * **Expectations come from somewhere else.** The encode side is generated by
 * `llama-tokenize` with `vocab_only`, a separate short-lived process that never
 * contacts the server; the decode side comes from the artifact's own token
 * table. Neither authority is the backend under test. A suite whose
 * expectations came from the live backend is a tautology — it passes whatever
 * that backend does, including the substitution — and is refused here rather
 * than merely discouraged in a comment.
 *
 * **The claim is bounded.** A finite corpus is behavioural evidence, not proof
 * of equivalence; `coverageNote` travels with the result so the bound cannot be
 * lost between here and a qualification report.
 */
import { createHash } from 'node:crypto';
import {
  BASE64_IMPLEMENTATION, decodeBase64, platformBase64Disagrees, toHex,
} from '@bokahli/velum/base64';
import {
  canaryReferenceIsIndependent,
  canarySuiteIdentity,
  TOKENIZER_CANARY_SCHEMA,
  type CanaryReference,
  type TokenizerCanaryResult,
  type TokenizerCanarySuite,
} from '@bokahli/contracts';

// Re-exported so the generator and the loader reach one implementation of the
// identity rule. Two would eventually disagree, and the day they did, one of
// them would be the one deciding whether a canary's label is true.
export { canarySuiteIdentity, canaryCorpusDigest } from '@bokahli/contracts';

export const CANARY_COVERAGE_NOTE =
  'Behavioural canary coverage over a fixed corpus, in both directions. It ' +
  'establishes that these exact inputs produce these exact token ids, and ' +
  'these exact ids produce these exact bytes, on this backend instance. It is ' +
  'not a proof of tokenizer equivalence: a substitution that changes ' +
  'segmentation only outside the corpus is not detected.';

/** At most this many failing case ids travel in a result. */
const MAX_REPORTED_FAILURES = 8;

export interface CanaryProbeSources {
  /** POST /tokenize with the suite's pinned settings. Returns token ids. */
  readonly tokenize: (
    text: string,
    opts: {
      readonly addSpecial: boolean;
      readonly parseSpecial: boolean;
      /** Ids at or above this are not ids for this vocabulary. */
      readonly vocabSize?: number;
    },
  ) => Promise<readonly number[]>;
  /** POST /detokenize. Returns the text for those ids. */
  readonly detokenize: (ids: readonly number[]) => Promise<string>;
  readonly now: () => Date;
}

export interface CanaryBinding {
  /** Digest of the artifact the backend was attested to be serving. */
  readonly artifactDigest: string;
  /** Tokenizer metadata digest read from that artifact. */
  readonly tokenizerMetadataDigest: string | null;
  /** The instance being verified. */
  readonly backendInstanceId: string | null;
}

/**
 * Canonical form of everything a suite asserts, except its own hash.
 *
 * Field order is fixed here rather than taken from key order, so a suite
 * rewritten by a tool that reorders JSON keys still hashes the same — and so a
 * field added later cannot slip in unhashed.
 */
export function canonicalCanaryPayload(suite: TokenizerCanarySuite): string {
  const ref = (r: CanaryReference): string =>
    [
      r.method,
      (r.generatorComponents ?? []).join(','),
      r.generatorDigest ?? '',
      r.generatorBuild ?? '',
      r.producedByBackendInstanceId ?? '',
    ].join('|');
  return [
    `schema=${suite.schemaVersion}`,
    `suiteId=${suite.suiteId}`,
    // The family claim is inside the hash, not beside it. A suite whose label
    // was corrected without regenerating its expectations must not still
    // validate: the point of the correction is that the two agree.
    `tokenizerFamily=${suite.tokenizerFamily ?? ''}`,
    `tokenizerPre=${suite.tokenizerPre ?? ''}`,
    `artifactDigest=${suite.artifactDigest}`,
    `tokenizerMetadataDigest=${suite.tokenizerMetadataDigest}`,
    `vocabSize=${String(suite.vocabSize)}`,
    `addSpecial=${String(suite.encodeSettings.addSpecial)}`,
    `parseSpecial=${String(suite.encodeSettings.parseSpecial)}`,
    `encodeReference=${ref(suite.encodeReference)}`,
    `decodeReference=${ref(suite.decodeReference)}`,
    ...suite.encode.map((c) => `encode:${c.id}:${c.inputBase64}:${c.expectedIds.join(',')}`),
    ...suite.decode.map((c) => `decode:${c.id}:${String(c.tokenId)}:${c.expectedBytesBase64}`),
  ].join('\n');
}

export function canaryPayloadHash(suite: TokenizerCanarySuite): string {
  return `sha256:${createHash('sha256').update(canonicalCanaryPayload(suite)).digest('hex')}`;
}

/**
 * Structural validation, for the loader.
 *
 * Runs where a bad suite is a configuration error rather than a verdict, so
 * that a malformed canary is refused at startup instead of quietly producing
 * `encodeCanaryVerified: false` forever and looking like a tokenizer problem.
 */
export function validateCanarySuite(suite: unknown): readonly string[] {
  const errs: string[] = [];
  const s = suite as TokenizerCanarySuite | null;
  if (s === null || typeof s !== 'object') return ['canary suite is not an object'];
  if (s.schemaVersion !== TOKENIZER_CANARY_SCHEMA) {
    errs.push(`unknown canary schema ${String(s.schemaVersion)}`);
  }
  if (typeof s.suiteId !== 'string' || s.suiteId.length === 0) errs.push('suite has no suiteId');
  if (typeof s.artifactDigest !== 'string') errs.push('suite names no artifact digest');
  if (!Array.isArray(s.encode) || s.encode.length === 0) errs.push('suite has no encode cases');
  if (!Array.isArray(s.decode) || s.decode.length === 0) errs.push('suite has no decode cases');
  if (typeof s.payloadHash !== 'string') errs.push('suite carries no payload hash');
  if (errs.length > 0) return errs;

  // Nothing may travel in a suite that the hash does not cover. The canonical
  // payload names its fields explicitly — which is what makes it stable against
  // key reordering — and the cost of that is that a field nobody listed would
  // ride along unhashed. Unknown keys are therefore refused outright rather
  // than ignored, so adding a field to this contract forces adding it to the
  // preimage.
  const SUITE_KEYS = new Set([
    'schemaVersion', 'suiteId', 'tokenizerFamily', 'tokenizerPre',
    'artifactDigest', 'tokenizerMetadataDigest', 'vocabSize',
    'encodeSettings', 'encodeReference', 'decodeReference', 'encode', 'decode',
    'payloadHash', 'generatedAt', 'coverage', 'note',
  ]);
  const ENCODE_KEYS = new Set(['id', 'note', 'inputBase64', 'expectedIds']);
  const DECODE_KEYS = new Set(['id', 'note', 'tokenId', 'expectedBytesBase64']);
  const REF_KEYS = new Set([
    'method', 'generatorComponents', 'generatorDigest', 'generatorBuild',
    'producedByBackendInstanceId', 'note',
  ]);
  // Every pinned encoding must be canonical base64 under the audited codec.
  // A permissive decoder accepts several spellings of the same bytes, so a
  // corrupted character could still decode to something plausible; a suite that
  // cannot be read exactly is not expectations, it is a guess.
  for (const c of s.encode) {
    if (typeof c?.inputBase64 !== 'string' || decodeCanonical(c.inputBase64) === null) {
      errs.push(`${NON_CANONICAL_PREFIX}: encode case ${String(c?.id)} inputBase64`);
    }
  }
  for (const c of s.decode) {
    if (typeof c?.expectedBytesBase64 !== 'string' || decodeCanonical(c.expectedBytesBase64) === null) {
      errs.push(`${NON_CANONICAL_PREFIX}: decode case ${String(c?.id)} expectedBytesBase64`);
    }
  }

  const unknown = (obj: object, allowed: Set<string>, where: string): void => {
    for (const k of Object.keys(obj)) {
      if (!allowed.has(k)) errs.push(`unknown field ${where}.${k} would not be covered by the hash`);
    }
  };
  unknown(s, SUITE_KEYS, 'suite');
  unknown(s.encodeReference ?? {}, REF_KEYS, 'encodeReference');
  unknown(s.decodeReference ?? {}, REF_KEYS, 'decodeReference');
  for (const c of s.encode) unknown(c, ENCODE_KEYS, `encode[${c.id}]`);
  for (const c of s.decode) unknown(c, DECODE_KEYS, `decode[${c.id}]`);

  const seen = new Set<string>();
  for (const c of [...s.encode, ...s.decode]) {
    if (seen.has(c.id)) errs.push(`duplicate canary case id ${c.id}`);
    seen.add(c.id);
  }

  // Two cases over the same bytes that expect different ids cannot both be
  // right. One of them fails for ever, which reads as a tokenizer problem and
  // is a corpus problem — the kind of permanent red that gets a check disabled.
  const byInput = new Map<string, readonly number[]>();
  for (const c of s.encode) {
    const prior = byInput.get(c.inputBase64);
    if (prior !== undefined && prior.join(',') !== c.expectedIds.join(',')) {
      errs.push(`encode case ${c.id} expects different ids for an input already pinned`);
    }
    byInput.set(c.inputBase64, c.expectedIds);
  }
  const byId = new Map<number, string>();
  for (const c of s.decode) {
    const prior = byId.get(c.tokenId);
    if (prior !== undefined && prior !== c.expectedBytesBase64) {
      errs.push(`decode case ${c.id} expects different bytes for an id already pinned`);
    }
    byId.set(c.tokenId, c.expectedBytesBase64);
  }

  // Ids must be ids: a negative or fractional expectation could never be met,
  // and one at or beyond the declared vocabulary describes another vocabulary.
  for (const c of s.encode) {
    if (!Array.isArray(c.expectedIds) || c.expectedIds.length === 0) {
      errs.push(`encode case ${c.id} pins no ids`);
      continue;
    }
    for (const v of c.expectedIds) {
      if (!Number.isSafeInteger(v) || v < 0 || v >= s.vocabSize) {
        errs.push(`encode case ${c.id} pins ${String(v)}, which is not an id in this vocabulary`);
        break;
      }
    }
  }
  for (const c of s.decode) {
    if (!Number.isSafeInteger(c.tokenId) || c.tokenId < 0 || c.tokenId >= s.vocabSize) {
      errs.push(`decode case ${c.id} names ${String(c.tokenId)}, not an id in this vocabulary`);
    }
  }

  // The label must be the one the contents produce.
  //
  // Before this check the suite id was authored, and every artifact in the
  // catalog — Gemma included — shipped a canary announcing `qwen35-broad.v1`.
  // Nothing underneath was wrong: the digest bindings were exact and a Qwen
  // suite could never have verified against a Gemma artifact. The *label* was
  // false, and a label is what a person reads out of an attestation. Deriving
  // it makes it a claim that can be checked; checking it here makes an
  // untruthful one a refusal rather than a display bug.
  if (
    (s.tokenizerFamily !== null && typeof s.tokenizerFamily !== 'string') ||
    (s.tokenizerPre !== null && typeof s.tokenizerPre !== 'string')
  ) {
    errs.push('tokenizerFamily and tokenizerPre must each be a string or null');
  } else if (typeof s.tokenizerMetadataDigest === 'string') {
    const derived = canarySuiteIdentity({
      tokenizerFamily: s.tokenizerFamily,
      tokenizerPre: s.tokenizerPre,
      tokenizerMetadataDigest: s.tokenizerMetadataDigest,
      encode: s.encode,
    });
    if (derived !== s.suiteId) {
      errs.push(
        `suiteId "${s.suiteId}" is not the identity this suite's contents produce ` +
          `("${derived}"): a canary may not name a tokenizer family, corpus or ` +
          'tokenizer metadata other than its own',
      );
    }
  }

  const recomputed = canaryPayloadHash(s);
  if (recomputed !== s.payloadHash) {
    errs.push(
      `canary payload hash does not match its contents (declared ${s.payloadHash}, ` +
        `computed ${recomputed}): the suite was edited without being regenerated`,
    );
  }
  return errs;
}

function unverified(
  observedAt: string,
  binding: CanaryBinding,
  suite: TokenizerCanarySuite | null,
  reasons: readonly string[],
  hostIntegrityFault: string | null = null,
): TokenizerCanaryResult {
  // One phrasing wherever a host fault is reported, so a reader grepping for it
  // finds every occurrence rather than the two thirds that took one path.
  const allReasons = hostIntegrityFault === null
    ? reasons
    : [`host integrity: ${hostIntegrityFault}`, ...reasons];
  return {
    schemaVersion: suite?.schemaVersion ?? null,
    canarySuiteId: suite?.suiteId ?? null,
    canarySuiteHash: suite?.payloadHash ?? null,
    decodeCanaryVerified: false,
    encodeCanaryVerified: false,
    encodeChecked: 0,
    encodeMatched: 0,
    decodeChecked: 0,
    decodeMatched: 0,
    failedCaseIds: [],
    encodeReferenceMethod: suite?.encodeReference?.method ?? null,
    decodeReferenceMethod: suite?.decodeReference?.method ?? null,
    verifiedBackendInstanceId: binding.backendInstanceId,
    verifiedAt: observedAt,
    reasons: allReasons,
    hostIntegrityFault,
    baseEncodingImplementation: BASE64_IMPLEMENTATION,
    coverageNote: CANARY_COVERAGE_NOTE,
  };
}


/**
 * Run the canary. Never throws.
 *
 * A probe that could not run leaves the claim unproven, which is the correct
 * outcome and not an error a caller has to handle — a thrown exception here
 * would take down a response over a fact that is allowed to be unavailable.
 */
export async function verifyTokenizerCanary(
  suite: TokenizerCanarySuite | null,
  binding: CanaryBinding,
  sources: CanaryProbeSources,
): Promise<TokenizerCanaryResult> {
  const observedAt = sources.now().toISOString();

  if (suite === null) {
    return unverified(observedAt, binding, null, [
      'no tokenizer canary is pinned for this artifact, so the runtime was never ' +
        'asked to encode anything: prompt counts come from an unverified tokenizer',
    ]);
  }

  const structural = validateCanarySuite(suite);
  if (structural.length > 0) {
    // A pinned encoding that is not canonical is a fault in this machine or in
    // the corpus, not a runtime that segments text differently. Naming it as
    // such is what stops it degrading token provenance and pointing the
    // investigation at the tokenizer.
    const encodingFault = structural.find((e) => e.startsWith(NON_CANONICAL_PREFIX)) ?? null;
    return unverified(observedAt, binding, suite, structural, encodingFault);
  }

  const bindingReasons: string[] = [];
  if (suite.artifactDigest !== binding.artifactDigest) {
    // A suite is expectations *about one artifact*. Accepting one generated
    // for another would import a different model's segmentation as proof of
    // this one's.
    bindingReasons.push(
      'canary was generated for a different artifact digest; a canary is not portable',
    );
  }
  if (
    binding.tokenizerMetadataDigest !== null &&
    suite.tokenizerMetadataDigest !== binding.tokenizerMetadataDigest
  ) {
    bindingReasons.push(
      'canary was generated against different tokenizer metadata than the artifact now declares',
    );
  }
  if (binding.backendInstanceId === null) {
    bindingReasons.push('backend instance is unknown, so a canary result cannot be bound to it');
  }
  if (!canaryReferenceIsIndependent(suite.encodeReference.method)) {
    // The tautology. Expected values produced by the backend under test pass
    // whatever that backend does, substitution included.
    bindingReasons.push(
      `encode expectations came from ${suite.encodeReference.method}, which is not ` +
        'independent of the backend being verified: evidence cannot authorise itself',
    );
  }
  if (!canaryReferenceIsIndependent(suite.decodeReference.method)) {
    bindingReasons.push(
      `decode expectations came from ${suite.decodeReference.method}, which is not ` +
        'independent of the backend being verified',
    );
  }
  for (const [side, r] of [
    ['encode', suite.encodeReference],
    ['decode', suite.decodeReference],
  ] as const) {
    if (
      r.producedByBackendInstanceId !== null &&
      binding.backendInstanceId !== null &&
      r.producedByBackendInstanceId === binding.backendInstanceId
    ) {
      bindingReasons.push(
        `${side} expectations were produced by the very backend instance being verified`,
      );
    }
  }
  if (bindingReasons.length > 0) return unverified(observedAt, binding, suite, bindingReasons);

  const reasons: string[] = [];
  const failed: string[] = [];

  // --- decode: token id -> bytes ------------------------------------------
  // Set when the *host* is at fault rather than the runtime: a non-canonical
  // pinned encoding, or a platform base64 encoder that disagrees with the
  // audited one. Either is a statement about this machine, and neither may be
  // reported as the tokenizer disagreeing with anything.
  let hostIntegrity: string | null = null;

  // A cheap probe, run once per canary rather than per case. It does not gate
  // any comparison — those use the audited codec — it exists so that a host
  // miscomputing base64 becomes a typed fault instead of a mystery.
  {
    const probe = platformBase64Disagrees(new TextEncoder().encode(HOST_PROBE_INPUT));
    if (probe !== null) {
      hostIntegrity =
        'the platform base64 encoder disagrees with the audited implementation on a ' +
        'fixed input; this host is miscomputing conversions and no measurement taken ' +
        'on it can be attributed to the runtime or the model';
    }
  }

  let decodeMatched = 0;
  let decodeChecked = 0;
  let decodeUsable = true;
  for (const c of suite.decode) {
    decodeChecked += 1;
    let got: string;
    try {
      got = await sources.detokenize([c.tokenId]);
    } catch (err) {
      decodeUsable = false;
      reasons.push(`runtime detokenize failed (${(err as Error).name})`);
      break;
    }
    // Compared as lowercase hex over bytes, not as base64 strings.
    //
    // `Buffer.prototype.toString('base64')` returns a wrong character roughly
    // once in a thousand calls on one physical core of this machine — silent,
    // no machine check, source bytes provably unchanged. This comparison
    // decides `decodeCanaryVerified`, which decides Luak's token provenance,
    // so a host fault here used to surface as a tokenizer that "disagrees with
    // the artifact token table" and discard an otherwise valid attempt.
    // Hex is one spelling per byte and uses no vectorised conversion.
    const expected = decodeCanonical(c.expectedBytesBase64);
    if (expected === null) {
      hostIntegrity ??= `canary case ${c.id} carries a non-canonical expectedBytesBase64`;
      break;
    }
    const gotBytes = new TextEncoder().encode(got);
    if (toHex(gotBytes) === toHex(expected)) decodeMatched += 1;
    else if (failed.length < MAX_REPORTED_FAILURES) failed.push(c.id);
  }

  // --- encode: bytes -> token ids -----------------------------------------
  let encodeMatched = 0;
  let encodeChecked = 0;
  let encodeUsable = true;
  for (const c of suite.encode) {
    encodeChecked += 1;
    const inputBytes = decodeCanonical(c.inputBase64);
    if (inputBytes === null) {
      hostIntegrity ??= `canary case ${c.id} carries a non-canonical inputBase64`;
      break;
    }
    const text = new TextDecoder('utf-8').decode(inputBytes);
    let got: readonly number[];
    try {
      got = await sources.tokenize(text, {
        addSpecial: suite.encodeSettings.addSpecial,
        parseSpecial: suite.encodeSettings.parseSpecial,
        vocabSize: suite.vocabSize,
      });
    } catch (err) {
      encodeUsable = false;
      reasons.push(`runtime tokenize failed (${(err as Error).name})`);
      break;
    }
    const same =
      got.length === c.expectedIds.length && got.every((v, i) => v === c.expectedIds[i]);
    if (same) encodeMatched += 1;
    else if (failed.length < MAX_REPORTED_FAILURES) failed.push(c.id);
  }

  // No partial credit in either direction. A suite where one encode case fails
  // describes a runtime that segments text differently from the one the
  // expectations came from; that is the finding, not a rounding error.
  // A host that cannot convert bytes reliably has not told us anything about
  // the runtime. Both canaries are unverified, the reason says why, and the
  // caller turns it into a runtime-unhealthy outcome rather than degraded
  // token provenance. Nothing here is ever attributed to the model.
  const decodeVerified = hostIntegrity === null && decodeUsable && decodeChecked > 0 && decodeMatched === decodeChecked;
  const encodeVerified = hostIntegrity === null && encodeUsable && encodeChecked > 0 && encodeMatched === encodeChecked;
  if (hostIntegrity !== null) reasons.push(`host integrity: ${hostIntegrity}`);

  if (!decodeVerified && decodeUsable && hostIntegrity === null) {
    reasons.push(
      `runtime decoding disagrees with the artifact token table ` +
        `(${decodeMatched}/${decodeChecked} cases matched)`,
    );
  }
  if (!encodeVerified && encodeUsable && hostIntegrity === null) {
    reasons.push(
      `runtime encoding disagrees with the pinned canary ` +
        `(${encodeMatched}/${encodeChecked} cases matched): the runtime segments text ` +
        'differently from the tokenizer this artifact declares',
    );
  }

  return {
    schemaVersion: suite.schemaVersion,
    canarySuiteId: suite.suiteId,
    canarySuiteHash: suite.payloadHash,
    decodeCanaryVerified: decodeVerified,
    encodeCanaryVerified: encodeVerified,
    encodeChecked,
    encodeMatched,
    decodeChecked,
    decodeMatched,
    failedCaseIds: failed,
    encodeReferenceMethod: suite.encodeReference.method,
    decodeReferenceMethod: suite.decodeReference.method,
    verifiedBackendInstanceId: binding.backendInstanceId,
    verifiedAt: observedAt,
    reasons,
    hostIntegrityFault: hostIntegrity,
    baseEncodingImplementation: BASE64_IMPLEMENTATION,
    coverageNote: CANARY_COVERAGE_NOTE,
  };
}

/**
 * Decode a pinned canary encoding, or null when it is not canonical base64.
 *
 * Strict on purpose. A permissive decoder accepts several spellings of the same
 * bytes, so a corrupted character in a pinned suite could still decode to
 * something plausible; this one refuses, and the refusal is a host or corpus
 * fault rather than a quiet substitution.
 */
function decodeCanonical(text: string): Uint8Array | null {
  try {
    return decodeBase64(text);
  } catch {
    return null;
  }
}

/** Marks a structural error as an encoding fault rather than a suite-shape one. */
const NON_CANONICAL_PREFIX = 'a pinned canary encoding is not canonical base64';

/** A fixed input for the host probe. Nothing secret, nothing derived. */
const HOST_PROBE_INPUT = 'bokahli tokenizer canary host integrity probe 0123456789';
