/**
 * Verify a pinned tokenizer canary against the running backend.
 *
 * The canary is two-sided on purpose. f270ee9's probe asked the runtime to
 * decode sampled ids and compared the bytes; that is a real check and it is
 * blind in the direction that matters. Prompt counts come from encoding, and
 * `--override-kv` can replace `tokenizer.ggml.merges`, `tokenizer.ggml.pre`,
 * or the added-token configuration at load time while leaving the token table —
 * the only thing a decode probe reads — completely untouched. Every decode
 * sample passes; every count is wrong.
 *
 * So this module checks both directions, and reports them as two booleans that
 * cannot be substituted for one another.
 *
 * **Expectations come from somewhere else.** The encode side is generated by
 * `llama-tokenize` with `vocab_only`, a separate short-lived process that never
 * contacts the server; the decode side comes from the artifact's own token
 * table. Neither authority is the backend under test. A suite whose
 * expectations came from the live backend is a tautology — it passes whatever
 * that backend does, including the substitution — and is refused here rather
 * than merely discouraged in a comment.
 *
 * **The claim is bounded.** A finite corpus is behavioural evidence, not proof
 * of equivalence; `coverageNote` travels with the result so the bound cannot be
 * lost between here and a qualification report.
 */
import { createHash } from 'node:crypto';
import {
  canaryReferenceIsIndependent,
  TOKENIZER_CANARY_SCHEMA,
  type CanaryReference,
  type TokenizerCanaryResult,
  type TokenizerCanarySuite,
} from '@bokahli/contracts';

export const CANARY_COVERAGE_NOTE =
  'Behavioural canary coverage over a fixed corpus, in both directions. It ' +
  'establishes that these exact inputs produce these exact token ids, and ' +
  'these exact ids produce these exact bytes, on this backend instance. It is ' +
  'not a proof of tokenizer equivalence: a substitution that changes ' +
  'segmentation only outside the corpus is not detected.';

/** At most this many failing case ids travel in a result. */
const MAX_REPORTED_FAILURES = 8;

export interface CanaryProbeSources {
  /** POST /tokenize with the suite's pinned settings. Returns token ids. */
  readonly tokenize: (
    text: string,
    opts: { readonly addSpecial: boolean; readonly parseSpecial: boolean },
  ) => Promise<readonly number[]>;
  /** POST /detokenize. Returns the text for those ids. */
  readonly detokenize: (ids: readonly number[]) => Promise<string>;
  readonly now: () => Date;
}

export interface CanaryBinding {
  /** Digest of the artifact the backend was attested to be serving. */
  readonly artifactDigest: string;
  /** Tokenizer metadata digest read from that artifact. */
  readonly tokenizerMetadataDigest: string | null;
  /** The instance being verified. */
  readonly backendInstanceId: string | null;
}

/**
 * Canonical form of everything a suite asserts, except its own hash.
 *
 * Field order is fixed here rather than taken from key order, so a suite
 * rewritten by a tool that reorders JSON keys still hashes the same — and so a
 * field added later cannot slip in unhashed.
 */
export function canonicalCanaryPayload(suite: TokenizerCanarySuite): string {
  const ref = (r: CanaryReference): string =>
    [
      r.method,
      (r.generatorComponents ?? []).join(','),
      r.generatorDigest ?? '',
      r.generatorBuild ?? '',
      r.producedByBackendInstanceId ?? '',
    ].join('|');
  return [
    `schema=${suite.schemaVersion}`,
    `suiteId=${suite.suiteId}`,
    `artifactDigest=${suite.artifactDigest}`,
    `tokenizerMetadataDigest=${suite.tokenizerMetadataDigest}`,
    `vocabSize=${String(suite.vocabSize)}`,
    `addSpecial=${String(suite.encodeSettings.addSpecial)}`,
    `parseSpecial=${String(suite.encodeSettings.parseSpecial)}`,
    `encodeReference=${ref(suite.encodeReference)}`,
    `decodeReference=${ref(suite.decodeReference)}`,
    ...suite.encode.map((c) => `encode:${c.id}:${c.inputBase64}:${c.expectedIds.join(',')}`),
    ...suite.decode.map((c) => `decode:${c.id}:${String(c.tokenId)}:${c.expectedBytesBase64}`),
  ].join('\n');
}

export function canaryPayloadHash(suite: TokenizerCanarySuite): string {
  return `sha256:${createHash('sha256').update(canonicalCanaryPayload(suite)).digest('hex')}`;
}

/**
 * Structural validation, for the loader.
 *
 * Runs where a bad suite is a configuration error rather than a verdict, so
 * that a malformed canary is refused at startup instead of quietly producing
 * `encodeCanaryVerified: false` forever and looking like a tokenizer problem.
 */
export function validateCanarySuite(suite: unknown): readonly string[] {
  const errs: string[] = [];
  const s = suite as TokenizerCanarySuite | null;
  if (s === null || typeof s !== 'object') return ['canary suite is not an object'];
  if (s.schemaVersion !== TOKENIZER_CANARY_SCHEMA) {
    errs.push(`unknown canary schema ${String(s.schemaVersion)}`);
  }
  if (typeof s.suiteId !== 'string' || s.suiteId.length === 0) errs.push('suite has no suiteId');
  if (typeof s.artifactDigest !== 'string') errs.push('suite names no artifact digest');
  if (!Array.isArray(s.encode) || s.encode.length === 0) errs.push('suite has no encode cases');
  if (!Array.isArray(s.decode) || s.decode.length === 0) errs.push('suite has no decode cases');
  if (typeof s.payloadHash !== 'string') errs.push('suite carries no payload hash');
  if (errs.length > 0) return errs;
  const seen = new Set<string>();
  for (const c of [...s.encode, ...s.decode]) {
    if (seen.has(c.id)) errs.push(`duplicate canary case id ${c.id}`);
    seen.add(c.id);
  }
  const recomputed = canaryPayloadHash(s);
  if (recomputed !== s.payloadHash) {
    errs.push(
      `canary payload hash does not match its contents (declared ${s.payloadHash}, ` +
        `computed ${recomputed}): the suite was edited without being regenerated`,
    );
  }
  return errs;
}

function unverified(
  observedAt: string,
  binding: CanaryBinding,
  suite: TokenizerCanarySuite | null,
  reasons: readonly string[],
): TokenizerCanaryResult {
  return {
    schemaVersion: suite?.schemaVersion ?? null,
    canarySuiteId: suite?.suiteId ?? null,
    canarySuiteHash: suite?.payloadHash ?? null,
    decodeCanaryVerified: false,
    encodeCanaryVerified: false,
    encodeChecked: 0,
    encodeMatched: 0,
    decodeChecked: 0,
    decodeMatched: 0,
    failedCaseIds: [],
    encodeReferenceMethod: suite?.encodeReference?.method ?? null,
    decodeReferenceMethod: suite?.decodeReference?.method ?? null,
    verifiedBackendInstanceId: binding.backendInstanceId,
    verifiedAt: observedAt,
    reasons,
    coverageNote: CANARY_COVERAGE_NOTE,
  };
}

/**
 * Run the canary. Never throws.
 *
 * A probe that could not run leaves the claim unproven, which is the correct
 * outcome and not an error a caller has to handle — a thrown exception here
 * would take down a response over a fact that is allowed to be unavailable.
 */
export async function verifyTokenizerCanary(
  suite: TokenizerCanarySuite | null,
  binding: CanaryBinding,
  sources: CanaryProbeSources,
): Promise<TokenizerCanaryResult> {
  const observedAt = sources.now().toISOString();

  if (suite === null) {
    return unverified(observedAt, binding, null, [
      'no tokenizer canary is pinned for this artifact, so the runtime was never ' +
        'asked to encode anything: prompt counts come from an unverified tokenizer',
    ]);
  }

  const structural = validateCanarySuite(suite);
  if (structural.length > 0) return unverified(observedAt, binding, suite, structural);

  const bindingReasons: string[] = [];
  if (suite.artifactDigest !== binding.artifactDigest) {
    // A suite is expectations *about one artifact*. Accepting one generated
    // for another would import a different model's segmentation as proof of
    // this one's.
    bindingReasons.push(
      'canary was generated for a different artifact digest; a canary is not portable',
    );
  }
  if (
    binding.tokenizerMetadataDigest !== null &&
    suite.tokenizerMetadataDigest !== binding.tokenizerMetadataDigest
  ) {
    bindingReasons.push(
      'canary was generated against different tokenizer metadata than the artifact now declares',
    );
  }
  if (binding.backendInstanceId === null) {
    bindingReasons.push('backend instance is unknown, so a canary result cannot be bound to it');
  }
  if (!canaryReferenceIsIndependent(suite.encodeReference.method)) {
    // The tautology. Expected values produced by the backend under test pass
    // whatever that backend does, substitution included.
    bindingReasons.push(
      `encode expectations came from ${suite.encodeReference.method}, which is not ` +
        'independent of the backend being verified: evidence cannot authorise itself',
    );
  }
  if (!canaryReferenceIsIndependent(suite.decodeReference.method)) {
    bindingReasons.push(
      `decode expectations came from ${suite.decodeReference.method}, which is not ` +
        'independent of the backend being verified',
    );
  }
  for (const [side, r] of [
    ['encode', suite.encodeReference],
    ['decode', suite.decodeReference],
  ] as const) {
    if (
      r.producedByBackendInstanceId !== null &&
      binding.backendInstanceId !== null &&
      r.producedByBackendInstanceId === binding.backendInstanceId
    ) {
      bindingReasons.push(
        `${side} expectations were produced by the very backend instance being verified`,
      );
    }
  }
  if (bindingReasons.length > 0) return unverified(observedAt, binding, suite, bindingReasons);

  const reasons: string[] = [];
  const failed: string[] = [];

  // --- decode: token id -> bytes ------------------------------------------
  let decodeMatched = 0;
  let decodeChecked = 0;
  let decodeUsable = true;
  for (const c of suite.decode) {
    decodeChecked += 1;
    let got: string;
    try {
      got = await sources.detokenize([c.tokenId]);
    } catch (err) {
      decodeUsable = false;
      reasons.push(`runtime detokenize failed (${(err as Error).name})`);
      break;
    }
    if (Buffer.from(got, 'utf8').toString('base64') === c.expectedBytesBase64) decodeMatched += 1;
    else if (failed.length < MAX_REPORTED_FAILURES) failed.push(c.id);
  }

  // --- encode: bytes -> token ids -----------------------------------------
  let encodeMatched = 0;
  let encodeChecked = 0;
  let encodeUsable = true;
  for (const c of suite.encode) {
    encodeChecked += 1;
    const text = Buffer.from(c.inputBase64, 'base64').toString('utf8');
    let got: readonly number[];
    try {
      got = await sources.tokenize(text, {
        addSpecial: suite.encodeSettings.addSpecial,
        parseSpecial: suite.encodeSettings.parseSpecial,
      });
    } catch (err) {
      encodeUsable = false;
      reasons.push(`runtime tokenize failed (${(err as Error).name})`);
      break;
    }
    const same =
      got.length === c.expectedIds.length && got.every((v, i) => v === c.expectedIds[i]);
    if (same) encodeMatched += 1;
    else if (failed.length < MAX_REPORTED_FAILURES) failed.push(c.id);
  }

  // No partial credit in either direction. A suite where one encode case fails
  // describes a runtime that segments text differently from the one the
  // expectations came from; that is the finding, not a rounding error.
  const decodeVerified = decodeUsable && decodeChecked > 0 && decodeMatched === decodeChecked;
  const encodeVerified = encodeUsable && encodeChecked > 0 && encodeMatched === encodeChecked;

  if (!decodeVerified && decodeUsable) {
    reasons.push(
      `runtime decoding disagrees with the artifact token table ` +
        `(${decodeMatched}/${decodeChecked} cases matched)`,
    );
  }
  if (!encodeVerified && encodeUsable) {
    reasons.push(
      `runtime encoding disagrees with the pinned canary ` +
        `(${encodeMatched}/${encodeChecked} cases matched): the runtime segments text ` +
        'differently from the tokenizer this artifact declares',
    );
  }

  return {
    schemaVersion: suite.schemaVersion,
    canarySuiteId: suite.suiteId,
    canarySuiteHash: suite.payloadHash,
    decodeCanaryVerified: decodeVerified,
    encodeCanaryVerified: encodeVerified,
    encodeChecked,
    encodeMatched,
    decodeChecked,
    decodeMatched,
    failedCaseIds: failed,
    encodeReferenceMethod: suite.encodeReference.method,
    decodeReferenceMethod: suite.decodeReference.method,
    verifiedBackendInstanceId: binding.backendInstanceId,
    verifiedAt: observedAt,
    reasons,
    coverageNote: CANARY_COVERAGE_NOTE,
  };
}
